version: "3.9"
services:
  simcom:
    container_name: "simcom"
    image: registry.git.rwth-aachen.de/benedikt.stuhrmann/master-thesis/simcom
    tty: true
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ../code:/opt/simcom
      - ../../../data:/opt/data
