version: "3.9"
services:
  lapredict:
    container_name: "lapredict"
    image: lapredict
    tty: true
    entrypoint: ["/home/jit-dp/mongodb/bin/mongod"]
    environment:
      - TZ=Europe/Berlin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ../code:/home/jit-dp/ISSTA21-JIT-DP
      - ../../../data:/opt/data
      - ../../../mongodb:/data/db
      - ../../../repositories/linux:/home/jit-dp/ISSTA21-JIT-DP/Data_Extraction/git_base/git_datasets/linux/linux
      - ../../../repositories/chromium:/home/jit-dp/ISSTA21-JIT-DP/Data_Extraction/git_base/git_datasets/chromium/chromium
      - ../../../repositories/ffmpeg:/home/jit-dp/ISSTA21-JIT-DP/Data_Extraction/git_base/git_datasets/ffmpeg/ffmpeg
      
