version: "3.1"

services:
  db:
    container_name: "mysql-db"
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/docker-entrypoint-initdb.d # init data on first startup
      - mysql-db:/var/lib/mysql # persist data

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=2G

volumes:
  mysql-db:
    external: true